management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  flyway:
    enabled: on

  http:
    client:
      connect-timeout: 5s
      read-timeout: 10s

  datasource:
    url: jdbc:postgresql://localhost:5432/ricash
    username: ricash
    password: secret
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9180/realms/Ricash
ricash:
  security:
    jwt:
      principal-claim-name: preferred_username
      authorities-claim-name: realm_access/roles
      authority-prefix: ""
      audience: ""
    cors:
      allowed-origins: http://localhost:5173,http://localhost:3000
