services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=ricash'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=ricash'
    ports:
      - '5432:5432'
  keycloak:
    image: 'quay.io/keycloak/keycloak:24.0.1'
    environment:
      - 'KEYCLOAK_ADMIN=admin'
      - 'KEYCLOAK_ADMIN_PASSWORD=admin'
      - 'KC_HOSTNAME=localhost'
    ports:
      - '9080:8080'
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev" ]